title: nemo.com
baseurl: ""
url: "https://nemo11122.github.io"
markdown: kramdown
theme: null
excerpt_separator: "<!-- more -->"

collections:
  categories:
    output: true

permalink: /:categories/:title/
